// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Website_Selling_Phones.Data;

#nullable disable

namespace Website_Selling_Phones.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Website_Selling_Phones.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Apple",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6860),
                            Description = "Latest iPhone with A17 Pro chip, titanium design, and advanced camera system",
                            ImageUrl = "https://via.placeholder.com/300x400/000000/FFFFFF?text=iPhone+15+Pro",
                            IsFeatured = true,
                            Model = "iPhone 15 Pro",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Samsung",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6887),
                            Description = "Powerful Android phone with S Pen, AI features, and 200MP camera",
                            ImageUrl = "https://via.placeholder.com/300x400/1a1a2e/FFFFFF?text=Galaxy+S24+Ultra",
                            IsFeatured = true,
                            Model = "Galaxy S24 Ultra",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1299.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Google",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6889),
                            Description = "Google's flagship with best-in-class AI photography and pure Android",
                            ImageUrl = "https://via.placeholder.com/300x400/4285f4/FFFFFF?text=Pixel+8+Pro",
                            IsFeatured = true,
                            Model = "Pixel 8 Pro",
                            Name = "Google Pixel 8 Pro",
                            Price = 899.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Brand = "OnePlus",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6891),
                            Description = "Fast and smooth performance with Hasselblad cameras",
                            ImageUrl = "https://via.placeholder.com/300x400/f50514/FFFFFF?text=OnePlus+12",
                            IsFeatured = false,
                            Model = "OnePlus 12",
                            Name = "OnePlus 12",
                            Price = 799.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Xiaomi",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6893),
                            Description = "Leica optics, Snapdragon 8 Gen 3, and premium design",
                            ImageUrl = "https://via.placeholder.com/300x400/ff6900/FFFFFF?text=Xiaomi+14+Ultra",
                            IsFeatured = false,
                            Model = "14 Ultra",
                            Name = "Xiaomi 14 Ultra",
                            Price = 1099.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Apple",
                            CreatedAt = new DateTime(2026, 5, 8, 18, 57, 35, 479, DateTimeKind.Local).AddTicks(6895),
                            Description = "Great iPhone experience with Dynamic Island and USB-C",
                            ImageUrl = "https://via.placeholder.com/300x400/000000/FFFFFF?text=iPhone+15",
                            IsFeatured = false,
                            Model = "iPhone 15",
                            Name = "iPhone 15",
                            Price = 799.99m,
                            StockQuantity = 60
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
